display_title: Git for AMPS
display_tagline: Free resources from power system professionals
github_repo_id: ieee-pes-amps
download_zip:
download_tar:
admin_name: Carleton Coffrin
admin_email: carleton [at] coffrin [dot] com
admin_github_username: ccoffrin